### ISSUE TITLE
Using MQTT with Openshift

### ISSUE THREAD

**Issue by WillNilges** [thingsboard/thingsboard-ce-k8s#16]
**Installation**

**Description**
I stood up a ThingsBoard Microservices deployment on OKD 4.5, set up a tenant, and a device. Everything is peachy with HTTP requests as far as I can tell. Doing the following works fine:

```
curl --insecure -v -X POST -d @telemetry.json https://tb-route-http-transport-thingsboard.apps.lab.okd.local/api/v1/<access token>/telemetry --header "Content-Type:application/json"
```
However, while the installation scripts provided an http route, they did not provide an mqtt route. So I added my own.

```
spec:
 host: tb-route-mqtt-transport-thingsboard.apps.lab.okd.local
  path: /api/v1
  to:
    kind: Service
    name: tb-mqtt-transport
    weight: 100
  port:
    targetPort: mqtt
  tls:
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - host: tb-route-mqtt-transport-thingsboard.apps.lab.okd.local
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2020-10-23T18:11:43Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps.lab.okd.local
```

And tried using Mosquitto

```
mosquitto_pub -d -h "tb-route-mqtt-transport-thingsboard.apps.lab.okd.local" -t "v1/devices/me/telemetry" -u "$ACCESS_TOKEN" -f "telemetry-data-as-object.json"
```

**However, that failed with an `Error: No route to host` and no other information.**

So I tried `mosquitto_pub` again with `tb-route-node-root-thingsboard.apps.lab.okd.local` since I could use CURL and HTTP with that route (also set up by the scripts). **But that also did not work.**

I also tried performing a Gatling test, and of course, that also did not work.

What am I doing wrong? How do I get this route to work? Do I even need to? Can anybody provide an example of how to get MQTT working on a microservices deployment?

**Environment**

 * OS:  OKD 4.5 on Fedora CoreOS 32 w/ Fedora Server 32 Services VM
 * ThingsBoard: 3.1.1
 * Browser: Firefox 80

I also have an [issue open](https://github.com/thingsboard/thingsboard/issues/3637) on the main Thingsboard repo.
